### ISSUE TITLE
SWIFT_VERSION

### ISSUE THREAD

**Issue by mengzhidaren** [pycampers/flutter-rx-ble#13]
`plugin_scaffold` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.
    - `rx_ble` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

**Comment by pbaker5** [comment]
I used this work around to get the iOS version working: [https://github.com/kiwi-bop/flutter_crashlytics/issues/22#issuecomment-508930744](https://github.com/kiwi-bop/flutter_crashlytics/issues/22#issuecomment-508930744)

**Comment by mengzhidaren** [comment]
I introduced rx_ble in IOS using flutter module, which was normal after running, but the dependency file was missing. There is no Rx Bluetooth Kit libraries, but Android is normal and running well.

**Comment by mengzhidaren** [comment]
The solution is that the environment is not configured properly.
