### ISSUE TITLE
requestMtu return value?

### ISSUE THREAD

**Issue by xzzh999** [pycampers/flutter-rx-ble#15]
Hi~ 
after i set the mtu to 512, the return value is 23,  is this mean modify failed? why?

**Comment by devxpy** [comment]
This library only calls the native functions in android/ios SDK. So it's likely that this is a bug in your hardware, and in a rare case, with the underlying OS.

**Comment by xzzh999** [comment]
It looks like the system set limit to this, i have to do the package split things..
