### ISSUE TITLE
Trying to connect to a turned off device

### ISSUE THREAD

**Issue by joaowd** [pycampers/flutter-rx-ble#5]
Since the connect method doesn't have a timeout, if I try to connect to a turned off device it keeps trying to connect without stoping.

**Comment by devxpy** [comment]
You can use dart's in-built [timeout](https://api.dartlang.org/stable/2.4.0/dart-async/Stream/timeout.html) for streams.

```dart
final stream = RxBle.connect(deviceId, autoConnect: true).timeout(
  timeout,
  onTimeout: (sink) {
      ...
  },
);

await for (final state in stream) {
    ...
}
```
